evergrid_rails/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'

  get '/auth/:provider/callback', to: 'session#create'
  delete '/sign_out', to: 'session#destroy'

  resources :datasets
  resources :datacenters

end

evergrid_rails/app/models/datacenter.rb
class Datacenter < ActiveRecord::Base
  DATACENTER_TYPES = {
    # db key => human readable label
    'carina' => 'app.getcarina.com'
  }.freeze

  belongs_to :user

  mount_uploader :carina_config, CarinaConfigUploader

  validates :name, :user,
            presence: true

  validates :datacenter_type,
            inclusion: {
              in: DATACENTER_TYPES.keys
            }

  validates :carina_config,
            presence: {
              if: -> (dc) { dc.datacenter_type == 'carina' }
            }
end

evergrid_rails/app/models/dataset.rb
class Dataset < ActiveRecord::Base
  belongs_to :user

  validates :name, :description, :user,
            presence: true
end

evergrid_rails/app/models/user.rb
class User < ActiveRecord::Base
  validates :github_uid, :email, :nickname, :name, :github_token, :auth_json,
            presence: true

  has_many :datasets
  has_many :datacenters

  class << self
    def get_by_oauth(data)
      user = User.find_or_initialize_by(github_uid: data.uid)
      user.assign_attributes(
        auth_json:    data.to_h,

        email:        data.info.email,
        nickname:     data.info.nickname,
        name:         data.info.name,

        github_token: data.credentials.token
      )
      user.save!
      user
    end
  end
end

evergrid_rails/app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  include Pundit
  after_action :verify_authorized
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def signed_in?
    current_user.present?
  end

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to root_path
  end
end

evergrid_rails/app/controllers/datacenters_controller.rb
class DatacentersController < ApplicationController
  before_action :load_datacenter,  only: [:show, :edit, :update, :destroy]
  before_action :build_datacenter, only: [:new, :create]

  respond_to :html

  def index
    @datacenters = policy_scope(Datacenter)
    authorize @datacenters
    respond_with(@datacenters)
  end

  def show
    authorize @datacenter
    respond_with(@datacenter)
  end

  def new
    respond_with(@datacenter)
  end

  def edit
  end

  def create
    @datacenter.update(permitted_attributes(@datacenter))
    respond_with(@datacenter)
  end

  def update
    @datacenter.update(permitted_attributes(@datacenter))
    respond_with(@datacenter)
  end

  def destroy
    @datacenter.destroy
    respond_with(@datacenter)
  end

  private

  def load_datacenter
    @datacenter = policy_scope(Datacenter).find(params[:id])
    authorize @datacenter
  end

  def build_datacenter
    @datacenter = Datacenter.new(user: current_user)
    authorize @datacenter
  end
end

evergrid_rails/app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :load_dataset,  only: [:show, :edit, :update, :destroy]
  before_action :build_dataset, only: [:new, :create]

  respond_to :html

  def index
    @datasets = policy_scope(Dataset)
    authorize @datasets
    respond_with(@datasets)
  end

  def show
    authorize @dataset
    respond_with(@dataset)
  end

  def new
    respond_with(@dataset)
  end

  def edit
  end

  def create
    @dataset.update(permitted_attributes(@dataset))
    respond_with(@dataset)
  end

  def update
    @dataset.update(permitted_attributes(@dataset))
    respond_with(@dataset)
  end

  def destroy
    @dataset.destroy
    respond_with(@dataset)
  end

  private

  def load_dataset
    @dataset = policy_scope(Dataset).find(params[:id])
    authorize @dataset
  end

  def build_dataset
    @dataset = Dataset.new(user: current_user)
    authorize @dataset
  end
end

evergrid_rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    authorize :home
  end
end

evergrid_rails/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    authorize :session
    user = User.get_by_oauth(auth_data)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    authorize :session
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth_data
    request.env['omniauth.auth']
  end
end

evergrid_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

evergrid_rails/app/views/datacenters/_form.html.slim
= bootstrap_form_for @datacenter do |f|
  = f.text_field :name
  = f.collection_select :datacenter_type, Datacenter::DATACENTER_TYPES.to_a, :first, :second
  
  - if @datacenter.carina_config?
    - filename = @datacenter.carina_config.file.filename
    = f.file_field :carina_config, help: "Uploaded version: #{filename}"
  - else
    = f.file_field :carina_config
  = f.hidden_field :carina_config_cache
  
  = f.submit

evergrid_rails/app/views/datacenters/edit.html.slim
.page-header
  h1 Editing datacenter

.col-sm-9
  == render 'form'
.col-sm-3
  = link_to 'Back', datacenters_path, class: 'btn btn-default btn-block'
  = link_to 'Destroy', @datacenter, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger btn-block'

evergrid_rails/app/views/datacenters/index.html.slim
.page-header
  h1
    | Listing datacenters

.row
  .col-sm-9
    == cell('datacenter', collection: @datacenters, in_index?: true)
  .col-sm-3
    = link_to 'New Datacenter', new_datacenter_path, class: 'btn btn-success btn-block'

evergrid_rails/app/views/datacenters/new.html.slim
.page-header
  h1 New datacenter

.col-sm-9
  == render 'form'
.col-sm-3
  = link_to 'Back', datacenters_path, class: 'btn btn-default btn-block'

evergrid_rails/app/views/datacenters/show.html.slim
.col-sm-9
  == cell('datacenter', @datacenter)
.col-sm-3
  = link_to 'Back', datacenters_path, class: 'btn btn-default btn-block'
  = link_to 'Edit', edit_datacenter_path(@datacenter), class: 'btn btn-default btn-block'
  = link_to 'Destroy', @datacenter, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger btn-block'

evergrid_rails/app/views/datasets/_form.html.slim
= bootstrap_form_for @dataset do |f|
  = f.text_field :name
  = f.text_area :description
  
  = f.submit

evergrid_rails/app/views/datasets/edit.html.slim
.page-header
  h1 Editing dataset

.col-sm-9
  == render 'form'
.col-sm-3
  = link_to 'Back', datasets_path, class: 'btn btn-default btn-block'
  = link_to 'Destroy', @dataset, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger btn-block'

evergrid_rails/app/views/datasets/index.html.slim
.page-header
  h1
    | Listing datasets

.row
  .col-sm-9
    == cell('dataset', collection: @datasets, in_index?: true)
  .col-sm-3
    = link_to 'New Dataset', new_dataset_path, class: 'btn btn-success btn-block'

evergrid_rails/app/views/datasets/new.html.slim
.page-header
  h1 New dataset

.col-sm-9
  == render 'form'
.col-sm-3
  = link_to 'Back', datasets_path, class: 'btn btn-default btn-block'

evergrid_rails/app/views/datasets/show.html.slim
.col-sm-9
  == cell('dataset', @dataset)
.col-sm-3
  = link_to 'Back', datasets_path, class: 'btn btn-default btn-block'
  = link_to 'Edit', edit_dataset_path(@dataset), class: 'btn btn-default btn-block'
  = link_to 'Destroy', @dataset, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger btn-block'

evergrid_rails/app/views/home/show.html.slim
.page-header
  h1 Main page
  
p Cool images and stuff will be here.

evergrid_rails/app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to 'Evergrid', root_path, class: 'navbar-brand'
    ul.nav.navbar-nav
      /li= link_to 'Projects', '#'
      - if policy(Dataset).index?
        li= link_to 'Datasets', datasets_path
      - if policy(Datacenter).index?
        li= link_to 'Datacenters', datacenters_path
    .navbar-right
      - if signed_in?
        = link_to current_user.name, '#', class: 'navbar-text'
        = link_to 'Sign Out', sign_out_path, method: :delete, class: 'btn btn-default navbar-btn'
      - else
        = link_to 'auth/github', class: 'btn btn-default navbar-btn'
          i.fa.fa-github
          | &nbsp;
          | Sign In
        
        

evergrid_rails/app/views/layouts/application.html.slim
doctype html
html
  head
    title Evergrid
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags

  body
    = render 'layouts/header'
    .container
      - if flash.any?
       - flash.each do |name, msg|
         div class="alert alert-#{name == 'alert' ? 'danger' : 'success'} alert-dismissible" role="alert"
           button.close type="button" data-dismiss="alert"
             span aria-hidden="true" &times;
             span.sr-only Close
           = msg
      = yield